// <auto-generated />
using System;
using FieldKit.Modules.Products;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldKit.Modules.Products.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260810115256_AddProductRowVersion")]
    partial class AddProductRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldKit.Infrastructure.ChangeSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Value")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId");

                    b.ToTable("change_sequence", "products");
                });

            modelBuilder.Entity("FieldKit.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_message", "products");
                });

            modelBuilder.Entity("FieldKit.Infrastructure.Tombstone", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "EntityType", "EntityId");

                    b.HasIndex("TenantId", "RowVersion");

                    b.ToTable("tombstone", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.AssortmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsMustStock")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductId");

                    b.HasIndex("TenantId", "ChannelId", "IsMustStock");

                    b.HasIndex("TenantId", "ChannelId", "ProductId")
                        .IsUnique();

                    b.ToTable("assortment_item", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("brand", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "ParentId", "Name")
                        .IsUnique();

                    b.ToTable("category", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.OutletAssortmentOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsMustStock")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OutletId");

                    b.HasIndex("TenantId", "ProductId");

                    b.HasIndex("TenantId", "OutletId", "ProductId")
                        .IsUnique();

                    b.ToTable("outlet_assortment_override", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EffectiveFrom");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("price_list", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PriceListAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("OutletId")
                        .HasColumnType("uuid")
                        .HasColumnName("outlet_id");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ChannelId");

                    b.HasIndex("TenantId", "OutletId");

                    b.HasIndex("TenantId", "PriceListId", "ChannelId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PriceListId", "OutletId")
                        .IsUnique();

                    b.ToTable("price_list_assignment", "products", t =>
                        {
                            t.HasCheckConstraint("ck_price_list_assignment_one_scope", "(\"channel_id\" IS NULL) <> (\"outlet_id\" IS NULL)");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PriceListLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductId");

                    b.HasIndex("TenantId", "PriceListId", "ProductId")
                        .IsUnique();

                    b.ToTable("price_list_line", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PackSize")
                        .HasColumnType("integer");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaxClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BrandId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique();

                    b.HasIndex("TenantId", "TaxClassId");

                    b.ToTable("product", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountOff")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_off");

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("buy_quantity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal?>("GetPercentOff")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("get_percent_off");

                    b.Property<Guid?>("GetProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("get_product_id");

                    b.Property<int?>("GetQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("get_quantity");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("PercentOff")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_off");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "GetProductId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.HasIndex("TenantId", "ValidFrom", "Priority");

                    b.ToTable("promotion", "products", t =>
                        {
                            t.HasCheckConstraint("ck_promotion_value_matches_type", "CASE \"type\" WHEN 'PercentOff' THEN \"percent_off\" IS NOT NULL AND \"amount_off\" IS NULL AND \"currency\" IS NULL AND \"buy_quantity\" IS NULL AND \"get_quantity\" IS NULL AND \"get_percent_off\" IS NULL WHEN 'FixedAmountOff' THEN \"amount_off\" IS NOT NULL AND \"currency\" IS NOT NULL AND \"percent_off\" IS NULL AND \"buy_quantity\" IS NULL AND \"get_quantity\" IS NULL AND \"get_percent_off\" IS NULL WHEN 'VolumeTiered' THEN \"percent_off\" IS NULL AND \"amount_off\" IS NULL AND \"currency\" IS NULL AND \"buy_quantity\" IS NULL AND \"get_quantity\" IS NULL AND \"get_percent_off\" IS NULL WHEN 'BuyXGetY' THEN \"percent_off\" IS NULL AND \"amount_off\" IS NULL AND \"currency\" IS NULL AND \"buy_quantity\" IS NOT NULL AND \"get_quantity\" IS NOT NULL AND \"get_percent_off\" IS NOT NULL ELSE FALSE END");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("OutletId")
                        .HasColumnType("uuid")
                        .HasColumnName("outlet_id");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ChannelId");

                    b.HasIndex("TenantId", "OutletId");

                    b.HasIndex("TenantId", "PromotionId", "ChannelId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PromotionId", "OutletId")
                        .IsUnique();

                    b.ToTable("promotion_assignment", "products", t =>
                        {
                            t.HasCheckConstraint("ck_promotion_assignment_one_scope", "(\"channel_id\" IS NULL) <> (\"outlet_id\" IS NULL)");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "ProductId");

                    b.HasIndex("TenantId", "PromotionId", "CategoryId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PromotionId", "ProductId")
                        .IsUnique();

                    b.ToTable("promotion_target", "products", t =>
                        {
                            t.HasCheckConstraint("ck_promotion_target_one_subject", "(\"product_id\" IS NULL) <> (\"category_id\" IS NULL)");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountOff")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_off");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentOff")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_off");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PromotionId", "MinQuantity")
                        .IsUnique();

                    b.ToTable("promotion_tier", "products", t =>
                        {
                            t.HasCheckConstraint("ck_promotion_tier_value", "((\"percent_off\" IS NULL) <> (\"amount_off\" IS NULL)) AND ((\"amount_off\" IS NULL) = (\"currency\" IS NULL))");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Products.TaxClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("tax_class", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TaxClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TaxClassId", "CountryCode");

                    b.HasIndex("TenantId", "TaxClassId", "CountryCode", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("tax_rate", "products");
                });

            modelBuilder.Entity("FieldKit.Modules.Products.AssortmentItem", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Category", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldKit.Modules.Products.OutletAssortmentOverride", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PriceListAssignment", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.PriceList", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PriceListId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PriceListLine", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.PriceList", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PriceListId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FieldKit.Modules.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Product", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Brand", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BrandId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldKit.Modules.Products.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldKit.Modules.Products.TaxClass", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaxClassId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldKit.Modules.Products.Promotion", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GetProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionAssignment", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Promotion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionTarget", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldKit.Modules.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldKit.Modules.Products.Promotion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.PromotionTier", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.Promotion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Products.TaxRate", b =>
                {
                    b.HasOne("FieldKit.Modules.Products.TaxClass", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TaxClassId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
