// <auto-generated />
using System;
using FieldKit.Modules.Audit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldKit.Modules.Audit.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260811093445_InitialAudit")]
    partial class InitialAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldKit.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_message", "audit");
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CategoryFacings")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeightSetVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "VisitId")
                        .IsUnique();

                    b.HasIndex("TenantId", "OutletId", "CapturedAtUtc");

                    b.ToTable("audit", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_category_facings", "\"CategoryFacings\" IS NULL OR \"CategoryFacings\" >= 0");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.AvailabilityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AuditId", "ProductId")
                        .IsUnique();

                    b.ToTable("audit_availability", "audit");
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.FacingsEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<int>("Facings")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AuditId", "ProductId")
                        .IsUnique();

                    b.ToTable("audit_facings", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_facings_count", "\"Facings\" >= 0");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.PriceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<long?>("ExpectedMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<long>("ObservedMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AuditId", "ProductId")
                        .IsUnique();

                    b.ToTable("audit_price", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_price_amounts", "\"ObservedMinorUnits\" >= 0 AND (\"ExpectedMinorUnits\" IS NULL OR \"ExpectedMinorUnits\" >= 0)");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.AvailabilityEntry", b =>
                {
                    b.HasOne("FieldKit.Modules.Audit.Audit", null)
                        .WithMany("Availability")
                        .HasForeignKey("TenantId", "AuditId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.FacingsEntry", b =>
                {
                    b.HasOne("FieldKit.Modules.Audit.Audit", null)
                        .WithMany("Facings")
                        .HasForeignKey("TenantId", "AuditId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.PriceEntry", b =>
                {
                    b.HasOne("FieldKit.Modules.Audit.Audit", null)
                        .WithMany("Prices")
                        .HasForeignKey("TenantId", "AuditId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Audit.Audit", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Facings");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
