using System.Text.Json;
using FieldKit.Modules.Audit.Contracts;
using FieldKit.Modules.Journey.Contracts;
using FieldKit.Modules.Sync;
using FieldKit.Modules.Visit.Contracts;

namespace FieldKit.Server.Tests;

/// <summary>
/// The C# half of the shared <c>/sync/push</c> wire vectors (<c>OFF-04</c>, sync engine §4) — W9
/// slice 12.
/// </summary>
/// <remarks>
/// <para>
/// <b>These vectors exist because the two suites each tested their own idea of the wire, and neither
/// tested the wire.</b> Two bugs shipped from that in one slice: the client put every payload under
/// <c>visit</c> whatever the type said, and <see cref="PushedMutation.Visit"/> had no default and was
/// therefore a *required* constructor argument to <c>System.Text.Json</c>. Every test on both sides
/// passed throughout.
/// </para>
/// <para>
/// <b>The payloads are hand-authored, and that is the whole design.</b> A vector generated by
/// serialising a constructed <c>PushedMutation</c> would write <c>"visit": null</c> into every case
/// and reproduce exactly the blindness being fixed — it is what the existing tests did. These are
/// written as a *device* sends them, omitting every property the mutation does not use, so the
/// required-member bug is a failing test rather than a 400 in a browser.
/// </para>
/// <para>
/// <b>Deserialised with the API's own options.</b> Reading these with default
/// <c>JsonSerializerOptions</c> would prove something about a serialiser the server does not use;
/// <see cref="WireOptions"/> mirrors <c>Program.cs</c>, and the property that matters —
/// <c>RespectNullableAnnotations</c> — is the one that decides whether an omitted property is a
/// bad request or a null.
/// </para>
/// </remarks>
public class SyncPushWireTests
{
    /// <summary>
    /// The serializer options the minimal API uses for these endpoints.
    /// </summary>
    /// <remarks>
    /// Kept in step with <c>Program.cs</c> by hand, and the risk of drift is real — but the
    /// alternative is booting the whole host to read one options object, which would make a
    /// millisecond test into a Testcontainers one. What the pairing protects is caught either way:
    /// <see cref="SyncPushJourneyTests"/> posts raw JSON through the real pipeline.
    /// </remarks>
    private static readonly JsonSerializerOptions WireOptions = new(JsonSerializerDefaults.Web)
    {
        RespectNullableAnnotations = true,

        /*
         * The one that decides this test's whole worth, and I had it missing on the first run.
         *
         * Without `RespectRequiredConstructorParameters`, a positional record parameter with no
         * default is happily left at `null` — so a payload omitting `visit` bound fine here while the
         * running API refused the identical bytes with a 400. The vectors passed against the exact
         * bug they were written for, until the sabotage pass replayed it and they did not fail.
         *
         * Mirroring `Program.cs` is therefore not tidiness: an options object that differs from the
         * host's in any respect makes every case below a statement about a serializer nobody uses.
         */
        RespectRequiredConstructorParameters = true,
    };

    public static TheoryData<string> Cases()
    {
        var data = new TheoryData<string>();
        foreach (var mutation in Vectors().GetProperty("mutations").EnumerateArray())
        {
            data.Add(mutation.GetProperty("name").GetString()!);
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void A_device_payload_binds_to_the_mutation_its_type_names(string name)
    {
        var vector = Vectors().GetProperty("mutations").EnumerateArray()
            .Single(entry => entry.GetProperty("name").GetString() == name);

        var wire = vector.GetProperty("wire").GetRawText();
        var expected = vector.GetProperty("expected");

        // The assertion the browser made for me, once: a payload the server cannot bind fails the
        // *whole batch* with a 400, which a device retries on every reconnect rather than recording
        // and stopping. Every case here omits the properties it does not use.
        var mutation = JsonSerializer.Deserialize<PushedMutation>(wire, WireOptions);

        Assert.NotNull(mutation);
        Assert.Equal(vector.GetProperty("wire").GetProperty("type").GetString(), mutation.Type);

        var slot = expected.GetProperty("slot").GetString();

        Assert.Equal(slot == "visit", mutation.Visit is not null);
        Assert.Equal(slot == "notVisited", mutation.NotVisited is not null);
        Assert.Equal(slot == "rescheduled", mutation.Rescheduled is not null);
        Assert.Equal(slot == "unplanned", mutation.Unplanned is not null);
        Assert.Equal(slot == "audit", mutation.Audit is not null);
    }

    [Fact]
    public void Every_payload_lands_under_the_property_its_type_names()
    {
        /*
         * The routing rule, stated once over the whole file rather than per case.
         *
         * `type` became a discriminator in W9 slice 9; before that it had one legal value and the
         * arms did not exist. What this asserts is that no case has drifted into naming one kind and
         * carrying another — which is precisely what the client did for a whole slice.
         */
        foreach (var vector in Vectors().GetProperty("mutations").EnumerateArray())
        {
            var type = vector.GetProperty("wire").GetProperty("type").GetString();
            var slot = vector.GetProperty("expected").GetProperty("slot").GetString();

            var expected = type switch
            {
                nameof(CapturedVisit) => "visit",
                nameof(NotVisitedCall) => "notVisited",
                nameof(RescheduledCall) => "rescheduled",
                nameof(UnplannedCall) => "unplanned",
                nameof(CapturedAudit) => "audit",
                _ => null,
            };

            Assert.Equal(expected, slot);
        }
    }

    [Fact]
    public void The_payloads_carry_only_the_property_they_need()
    {
        /*
         * The property that makes these files worth having, asserted about the *files*.
         *
         * A case that grew `"visit": null` alongside its own payload would still bind, still pass
         * every other test here, and quietly stop covering the bug this exists for — because a
         * server that requires `visit` accepts an explicit null perfectly well.
         */
        foreach (var vector in Vectors().GetProperty("mutations").EnumerateArray())
        {
            var slot = vector.GetProperty("expected").GetProperty("slot").GetString();
            var name = vector.GetProperty("name").GetString();

            var payloads = vector.GetProperty("wire").EnumerateObject()
                .Select(property => property.Name)
                .Where(property => property is "visit" or "notVisited" or "rescheduled" or "unplanned" or "audit")
                .ToList();

            Assert.Equal(slot is null ? [] : new List<string> { slot }, payloads);
            Assert.NotNull(name);
        }
    }

    private static JsonElement Vectors()
    {
        var path = Path.Combine(GeneratedVectorTests.VectorsDirectory(), "sync", "push.v1.json");

        return JsonDocument.Parse(File.ReadAllText(path)).RootElement;
    }
}
