using System.Net;
using System.Net.Http.Json;
using FieldKit.Modules.Outlets;
using FieldKit.Modules.Visit;
using FieldKit.Modules.Visit.Contracts;
using Microsoft.Extensions.DependencyInjection;

namespace FieldKit.Server.Tests;

/// <summary>
/// Counting the calls that were actually made (<c>VIS-10</c>, <c>JRN-04</c>) — W12 slice 2a.
/// </summary>
/// <remarks>
/// <para>
/// Coverage's <b>numerator</b>, and the half <see cref="JourneyCoverageTests"/> cannot see: Journey
/// never learns that a call was made, because a planned call has no <c>Visited</c> state and nothing
/// subscribes to <c>VisitCompleted</c> to give it one. The visit knows which call it claimed, so the
/// visit is what gets counted.
/// </para>
/// <para>
/// The planned-call ids here are minted rather than generated by Journey, which is the honest shape
/// for what this method promises: it counts <i>distinct claimed ids</i> and does not validate them.
/// Whether an id is a real call on a published plan is <c>IJourneyQuery.ForVisitAsync</c>'s question,
/// asked at check-in — before any of these rows exist.
/// </para>
/// </remarks>
[Collection(ServerCollection.Name)]
public class VisitCoverageTests(ServerFixture fixture)
{
    private const string Zone = "Europe/Bucharest";

    private static readonly Coordinates Shop = new(44.4638, 26.0946);

    private static readonly DateOnly MayFirst = new(2026, 5, 1);
    private static readonly DateOnly MayLast = new(2026, 5, 31);

    private static string Unique(string label) => $"{label}-{Guid.NewGuid():N}"[..18];

    private HttpClient Admin() => fixture.CreateAuthenticatedClient(fixture.AdminAccessToken);

    [Fact]
    public async Task A_call_visited_twice_covered_one_call()
    {
        /*
         * The reason this is `Distinct` rather than a row count.
         *
         * Nothing stops a rep checking in twice at the same shop against the same planned call, and
         * `BR-VIS-2`'s posture is to record rather than refuse — so the state is reachable. Counting
         * both would make coverage exceed the round that was promised, which reads as a team that
         * did more calls than existed.
         *
         * The second shop is here so the answer cannot be "1" for the wrong reason.
         */
        using var client = Admin();

        var outletId = await OutletAsync(client);
        var alsoMine = await OutletAsync(client);
        var call = Guid.CreateVersion7();

        await IngestAsync(outletId, new DateOnly(2026, 5, 4), call);
        await IngestAsync(outletId, new DateOnly(2026, 5, 4), call);
        await IngestAsync(alsoMine, new DateOnly(2026, 5, 5), Guid.CreateVersion7());

        Assert.Equal(2, await FulfilledAsync([outletId, alsoMine]));
    }

    [Fact]
    public async Task A_visit_nobody_planned_is_work_but_not_coverage()
    {
        /*
         * The asymmetry that makes this a separate question rather than a filter the caller applies.
         * An unplanned call is real work and shows up in `CountByOutcomeAsync`; what it has not done
         * is keep a promise, so it must not push coverage above 100%.
         *
         * Both counts are asserted against the same three visits, which is the only way to show that
         * the difference is a decision rather than a missing row.
         */
        using var client = Admin();

        var outletId = await OutletAsync(client);

        await IngestAsync(outletId, new DateOnly(2026, 5, 11), Guid.CreateVersion7());
        await IngestAsync(outletId, new DateOnly(2026, 5, 12), plannedVisitId: null);
        await IngestAsync(outletId, new DateOnly(2026, 5, 13), plannedVisitId: null);

        Assert.Equal(3, (await CountAsync([outletId])).Total);
        Assert.Equal(1, await FulfilledAsync([outletId]));
    }

    [Fact]
    public async Task Both_halves_of_coverage_answer_about_the_same_window()
    {
        // The two ends of the window, on the numerator side. A ratio built from two counts is only
        // meaningful if both were asked the same question, and the visit side reaches the day
        // through instants where Journey reaches it through a plain date — so the boundary is
        // asserted on both rather than assumed to be shared.
        using var client = Admin();

        var outletId = await OutletAsync(client);

        await IngestAsync(outletId, MayFirst, Guid.CreateVersion7());
        await IngestAsync(outletId, MayLast, Guid.CreateVersion7());
        await IngestAsync(outletId, MayLast.AddDays(1), Guid.CreateVersion7());

        Assert.Equal(2, await FulfilledAsync([outletId]));
        Assert.Equal(3, await FulfilledAsync([outletId], MayFirst, MayLast.AddDays(1)));
    }

    [Fact]
    public async Task No_shops_in_scope_covered_nothing()
    {
        // The same decision the outcome count makes, asserted here too: an empty scope is answered
        // rather than translated. The seeded visit is what stops the zero being an empty table.
        using var client = Admin();

        var outletId = await OutletAsync(client);

        await IngestAsync(outletId, new DateOnly(2026, 5, 18), Guid.CreateVersion7());

        Assert.Equal(1, await FulfilledAsync([outletId]));
        Assert.Equal(0, await FulfilledAsync([]));
    }

    private Task<int> FulfilledAsync(
        IReadOnlyCollection<Guid> outletIds, DateOnly? from = null, DateOnly? to = null) =>
        AsTenant.RunAsync(fixture, fixture.AdminAccessToken, services => services
            .GetRequiredService<IVisitQuery>()
            .CountFulfilledCallsAsync(outletIds, from ?? MayFirst, to ?? MayLast));

    private Task<VisitOutcomeCounts> CountAsync(IReadOnlyCollection<Guid> outletIds) =>
        AsTenant.RunAsync(fixture, fixture.AdminAccessToken, services => services
            .GetRequiredService<IVisitQuery>()
            .CountByOutcomeAsync(outletIds, MayFirst, MayLast));

    /// <summary>A visit that happened on <paramref name="on"/>, claiming a call or claiming none.</summary>
    private async Task IngestAsync(Guid outletId, DateOnly on, Guid? plannedVisitId)
    {
        var checkedIn = new DateTimeOffset(on.ToDateTime(new TimeOnly(9, 30)), TimeSpan.Zero);

        var captured = new CapturedVisit(
            VisitId: Guid.CreateVersion7(),
            OutletId: outletId,
            PlannedVisitId: plannedVisitId,
            CheckedInAtUtc: checkedIn,
            CheckInLatitude: Shop.Latitude,
            CheckInLongitude: Shop.Longitude,
            CheckInDistanceMetres: 0,
            WasInsideGeofence: true,
            OverrideReason: null,
            Steps: [],
            Outcome: nameof(VisitOutcome.Productive),
            OutcomeReason: null,
            CheckedOutAtUtc: checkedIn.AddMinutes(20),
            CheckOutLatitude: Shop.Latitude,
            CheckOutLongitude: Shop.Longitude);

        var result = await AsTenant.RunAsync(fixture, fixture.AdminAccessToken, services => services
            .GetRequiredService<IVisitIngest>()
            .IngestAsync(captured, AsTenant.SubjectOf(fixture.AdminAccessToken)));

        Assert.Equal(VisitIngestRefusal.None, result.Refusal);
    }

    private static async Task<Guid> OutletAsync(HttpClient client)
    {
        var channel = await client.PostAsJsonAsync(
            "/api/outlets/channels", new ChannelRequest(Unique("Channel")));

        var channelId = (await channel.Content.ReadFromJsonAsync<ChannelResponse>())!.Id;

        var created = await client.PostAsJsonAsync(
            "/api/outlets",
            new CreateOutletRequest(Unique("OUT"), "Corner Shop", channelId, Zone, Location: Shop));

        Assert.Equal(HttpStatusCode.Created, created.StatusCode);

        return (await created.Content.ReadFromJsonAsync<OutletResponse>())!.Id;
    }
}
