// <auto-generated />
using System;
using FieldKit.Modules.Visit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldKit.Modules.Visit.Migrations
{
    [DbContext(typeof(VisitDbContext))]
    [Migration("20260809023850_VisitCheckOut")]
    partial class VisitCheckOut
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("visit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldKit.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_message", "visit");
                });

            modelBuilder.Entity("FieldKit.Modules.Visit.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CheckInDistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CheckedInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CheckedOutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("GeofenceOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OutcomeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlannedVisitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("WasInsideGeofence")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OutletId", "CheckedInAtUtc");

                    b.HasIndex("TenantId", "UserId", "CheckedInAtUtc");

                    b.ToTable("visit", "visit", t =>
                        {
                            t.HasCheckConstraint("ck_visit_checked_out", "(\"Status\" = 'CheckedOut') = (\"CheckedOutAtUtc\" IS NOT NULL) AND (\"Status\" = 'CheckedOut') = (\"Outcome\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_visit_checkin_point", "(\"CheckInLatitude\" IS NULL) = (\"CheckInLongitude\" IS NULL)");

                            t.HasCheckConstraint("ck_visit_checkout_point", "(\"CheckOutLatitude\" IS NULL) = (\"CheckOutLongitude\" IS NULL)");

                            t.HasCheckConstraint("ck_visit_outcome_reason", "(\"Outcome\" IS NOT DISTINCT FROM 'NonProductive') = (\"OutcomeReason\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_visit_override_reason", "\"WasInsideGeofence\" = false OR \"GeofenceOverrideReason\" IS NULL");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Visit.VisitStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("visit_step", "visit", t =>
                        {
                            t.HasCheckConstraint("ck_visit_step_completed_at", "(\"Status\" = 'Completed') = (\"CompletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_visit_step_note_text", "\"Type\" <> 'Note' OR \"Status\" <> 'Completed' OR \"Notes\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Visit.VisitStep", b =>
                {
                    b.HasOne("FieldKit.Modules.Visit.Visit", null)
                        .WithMany("Steps")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Visit.Visit", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
