// <auto-generated />
using System;
using FieldKit.Modules.Visit;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldKit.Modules.Visit.Migrations
{
    [DbContext(typeof(VisitDbContext))]
    partial class VisitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("visit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldKit.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_message", "visit");
                });

            modelBuilder.Entity("FieldKit.Modules.Visit.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CheckInDistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CheckedInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("GeofenceOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlannedVisitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("WasInsideGeofence")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OutletId", "CheckedInAtUtc");

                    b.HasIndex("TenantId", "UserId", "CheckedInAtUtc");

                    b.ToTable("visit", "visit", t =>
                        {
                            t.HasCheckConstraint("ck_visit_checkin_point", "(\"CheckInLatitude\" IS NULL) = (\"CheckInLongitude\" IS NULL)");

                            t.HasCheckConstraint("ck_visit_override_reason", "\"WasInsideGeofence\" = false OR \"GeofenceOverrideReason\" IS NULL");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
