// <auto-generated />
using System;
using FieldKit.Modules.Journey;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldKit.Modules.Journey.Migrations
{
    [DbContext(typeof(JourneyDbContext))]
    [Migration("20260808200954_AddRepAnnotations")]
    partial class AddRepAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("journey")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldKit.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_message", "journey");
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Date")
                        .IsUnique();

                    b.ToTable("holiday", "journey");
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.JourneyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "FromDate");

                    b.ToTable("journey_plan", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_journey_plan_window", "\"to_date\" >= \"from_date\"");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.OutletFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitsPerCycle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OutletId")
                        .IsUnique();

                    b.ToTable("outlet_frequency", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_outlet_frequency_cycle", "\"CycleLengthDays\" >= 1 AND \"CycleLengthDays\" <= 365");

                            t.HasCheckConstraint("ck_outlet_frequency_visits", "\"VisitsPerCycle\" >= 1");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.PlanShortfall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JourneyPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<int>("Planned")
                        .HasColumnType("integer");

                    b.Property<int>("Required")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "JourneyPlanId");

                    b.ToTable("plan_shortfall", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_plan_shortfall_is_short", "\"Planned\" < \"Required\"");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.PlannedVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("JourneyPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotVisitedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("RescheduledFrom")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "JourneyPlanId", "Date");

                    b.ToTable("planned_visit", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_planned_visit_reason", "(\"Status\" = 'NotVisited') = (\"NotVisitedReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.SegmentFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitsPerCycle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Segment")
                        .IsUnique();

                    b.ToTable("segment_frequency", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_segment_frequency_cycle", "\"CycleLengthDays\" >= 1 AND \"CycleLengthDays\" <= 365");

                            t.HasCheckConstraint("ck_segment_frequency_visits", "\"VisitsPerCycle\" >= 1");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.WorkingCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("VisitsPerDay")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("working_days");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("working_calendar", "journey", t =>
                        {
                            t.HasCheckConstraint("ck_working_calendar_capacity", "\"VisitsPerDay\" >= 1 AND \"VisitsPerDay\" <= 50");
                        });
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.PlanShortfall", b =>
                {
                    b.HasOne("FieldKit.Modules.Journey.JourneyPlan", null)
                        .WithMany("Shortfalls")
                        .HasForeignKey("TenantId", "JourneyPlanId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.PlannedVisit", b =>
                {
                    b.HasOne("FieldKit.Modules.Journey.JourneyPlan", null)
                        .WithMany("Visits")
                        .HasForeignKey("TenantId", "JourneyPlanId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldKit.Modules.Journey.JourneyPlan", b =>
                {
                    b.Navigation("Shortfalls");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
